<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ReportHistory extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'report_type',
        'parameters',
        'student_count',
        'format',
        'template',
        'generated_at',
    ];

    protected $casts = [
        'parameters' => 'array',
        'generated_at' => 'datetime',
    ];

    /**
     * Get the user that generated the report
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Scope a query to only include reports of a specific type
     */
    public function scopeOfType($query, $type)
    {
        return $query->where('report_type', $type);
    }

    /**
     * Scope a query to only include reports generated by a specific user
     */
    public function scopeGeneratedBy($query, $userId)
    {
        return $query->where('user_id', $userId);
    }

    /**
     * Scope a query to only include reports generated in a date range
     */
    public function scopeGeneratedBetween($query, $startDate, $endDate)
    {
        return $query->whereBetween('generated_at', [$startDate, $endDate]);
    }

    /**
     * Get formatted generated date
     */
    public function getFormattedGeneratedAtAttribute()
    {
        return $this->generated_at->format('d M Y h:i A');
    }
}
